In [2]:
import numpy as np
import pandas as pd

In [129]:
dfTemp = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "department": ["HR", "IT", "Finance", "IT", "HR"],
    "salary": [50000, 60000, 70000, 80000, 90000],
    "age": [25, 30, 35, 40, 45]
})

dfTemp

      name department  salary  age
0    Alice         HR   50000   25
1      Bob         IT   60000   30
2  Charlie    Finance   70000   35
3    David         IT   80000   40
4      Eve         HR   90000   45

In [4]:
df = pd.read_csv("unclean_data_practice.csv")

In [5]:
df.head()

,id,name,age,city,gender,salary,joining_date,department
0,1,Hemil Ghori,22,SURAT,Male,30000,2025-01-15,AI/ML
1,2,rahul patel,NaN,surat,male,"35,000",15/02/2025,MERN
2,3,PRIYA SHAH,21,NaN,Female,₹42000,2025/03/10,AI/ML
3,4,Amit Kumar,twenty-four,AHMEDABAD,M,45000,2025-04-05,Data
4,5,Neha Patel,23,ahmedabad,F,NaN,05-05-2025,data

In [8]:
df.tail()

    id          name age       city  gender   salary joining_date department
25  26     Tina Shah  19      Surat  Female    27000   2025-07-15       data
26  27  Vishal Mehta  33      Delhi    Male    88000   2025-07-20       MERN
27  28    Maya Patel  26      surat  Female  invalid   2025-07-25      AI/ML
28  29  Rakesh Kumar  28  Ahmedabad    Male    72000   2025-08-05       Data
29  30    Nisha Shah  25       PUNE  Female    54000   2025-08-10      AI/ML

In [13]:
df.sample(5)

,id,name,age,city,gender,salary,joining_date,department
11,12,Arjun Mehta,29,Mumbai,Male,80000,2025-10-11,MERN
3,4,Amit Kumar,twenty-four,AHMEDABAD,M,45000,2025-04-05,Data
22,23,Nitin Shah,25,Bombay,Male,51000,2025-07-01,Data
2,3,PRIYA SHAH,21,NaN,Female,₹42000,2025/03/10,AI/ML
5,6,Raj Mehta,25,Mumbai,Male,50000,2025-06-12,MERN

In [14]:
df.head()

,id,name,age,city,gender,salary,joining_date,department
0,1,Hemil Ghori,22,SURAT,Male,30000,2025-01-15,AI/ML
1,2,rahul patel,NaN,surat,male,"35,000",15/02/2025,MERN
2,3,PRIYA SHAH,21,NaN,Female,₹42000,2025/03/10,AI/ML
3,4,Amit Kumar,twenty-four,AHMEDABAD,M,45000,2025-04-05,Data
4,5,Neha Patel,23,ahmedabad,F,NaN,05-05-2025,data

In [17]:
df.shape

(30, 8)

In [18]:
df.columns

Index(['id', 'name', 'age', 'city', 'gender', 'salary', 'joining_date',
       'department'],
      dtype='str')

In [19]:
df.info

<bound method DataFrame.info of     id           name          age         city  gender   salary  \
0    1   Hemil Ghori            22        SURAT    Male    30000
1    2    rahul patel          NaN        surat    male   35,000
2    3     PRIYA SHAH           21          NaN  Female   ₹42000
3    4     Amit Kumar  twenty-four    AHMEDABAD       M    45000
4    5     Neha Patel           23   ahmedabad        F      NaN
5    6      Raj Mehta           25       Mumbai    Male    50000
6    7    Kiran Joshi          150         Pune  Female   -10000
7    8       Dev Shah           27       mumbai    Male    60000
8    9    Sneha Desai           24        SURAT  Female
9   10    Vivek Singh           26        Delhi    male    70000
10  11      Riya Shah           22        surat  FEMALE    48000
11  12    Arjun Mehta           29       Mumbai    Male    80000
12  13    Mehul Patel           31    Ahmedabad    Male    90000
13  14     Pooja Shah           20         Pune  Female    25000
14  15      Jay Patel           28       Surat     Male    40000
15  16            NaN           27        Delhi    Male    65000
16  17    Anjali Shah           26          NaN  Female    52000
17  18    Rohan Patel           30    Ahmedabad    Male    75000
18  19                          24       Mumbai  Female    58000
19  20     Isha Mehta           23         Pune  Female    62000
20   1   Hemil Ghori            22        SURAT    Male    30000
21   2   Rahul Patel            22        SURAT    Male    35000
22  23     Nitin Shah           25       Bombay    Male    51000
23  24    Kajal Joshi           21         Pune  Female      NaN
24  25       Om Patel          999    Ahmedabad    Male  9999999
25  26      Tina Shah           19        Surat  Female    27000
26  27   Vishal Mehta           33        Delhi    Male    88000
27  28     Maya Patel           26        surat  Female  invalid
28  29   Rakesh Kumar           28    Ahmedabad    Male    72000
29  30     Nisha Shah           25         PUNE  Female    54000

    joining_date department
0     2025-01-15      AI/ML
1     15/02/2025       MERN
2     2025/03/10      AI/ML
3     2025-04-05       Data
4     05-05-2025       data
5     2025-06-12       MERN
6     2025-06-20      AI/ML
7   invalid-date      AI/ML
8     2025-08-01       Data
9            NaN       MERN
10    2025-09-10      AI/ML
11    2025-10-11       MERN
12    2025-10-15       Data
13    2025-11-01      AI/ML
14    2025-11-12       MERN
15    2025-11-20       Data
16    2025-12-01      AI/ML
17    2025-12-05       MERN
18    2025-12-10       Data
19    2025-12-15      AI/ML
20    2025-01-15      AI/ML
21    15/02/2025       MERN
22    2025-07-01       Data
23    2025-07-05      AI/ML
24    2025-07-10       MERN
25    2025-07-15       data
26    2025-07-20       MERN
27    2025-07-25      AI/ML
28    2025-08-05       Data
29    2025-08-10      AI/ML  >

In [22]:
df.dtypes

id              int64
name              str
age               str
city              str
gender            str
salary            str
joining_date      str
department        str
dtype: object

In [23]:
df.describe()

              id
count  30.000000
mean   14.166667
std     9.311037
min     1.000000
25%     6.250000
50%    13.500000
75%    22.250000
max    30.000000

In [24]:
df.describe(include="object")

C:\Users\HEMIL\AppData\Local\Temp\ipykernel_28256\3764884355.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

                 name age   city gender salary joining_date department
count              29  29     28     30     28           29         30
unique             28  17     13      6     27           27          4
top      Hemil Ghori   22  SURAT   Male  30000   2025-01-15      AI/ML
freq                2   4      4     14      2            2         12

In [25]:
df.describe(include="all")

,id,name,age,city,gender,salary,joining_date,department
count,30.000000,29,29,28,30,28,29,30
unique,NaN,28,17,13,6,27,27,4
top,NaN,Hemil Ghori,22,SURAT,Male,30000,2025-01-15,AI/ML
freq,NaN,2,4,4,14,2,2,12
mean,14.166667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,9.311037,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,6.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,13.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,22.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,30.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df["name"]

0      Hemil Ghori
1       rahul patel
2        PRIYA SHAH
3        Amit Kumar
4        Neha Patel
5         Raj Mehta
6       Kiran Joshi
7          Dev Shah
8       Sneha Desai
9       Vivek Singh
10        Riya Shah
11      Arjun Mehta
12      Mehul Patel
13       Pooja Shah
14        Jay Patel
15              NaN
16      Anjali Shah
17      Rohan Patel
18
19       Isha Mehta
20     Hemil Ghori
21     Rahul Patel
22       Nitin Shah
23      Kajal Joshi
24         Om Patel
25        Tina Shah
26     Vishal Mehta
27       Maya Patel
28     Rakesh Kumar
29       Nisha Shah
Name: name, dtype: str

In [27]:
df[["name", "age", "salary"]]

             name          age   salary
0    Hemil Ghori            22    30000
1     rahul patel          NaN   35,000
2      PRIYA SHAH           21   ₹42000
3      Amit Kumar  twenty-four    45000
4      Neha Patel           23      NaN
5       Raj Mehta           25    50000
6     Kiran Joshi          150   -10000
7        Dev Shah           27    60000
8     Sneha Desai           24
9     Vivek Singh           26    70000
10      Riya Shah           22    48000
11    Arjun Mehta           29    80000
12    Mehul Patel           31    90000
13     Pooja Shah           20    25000
14      Jay Patel           28    40000
15            NaN           27    65000
16    Anjali Shah           26    52000
17    Rohan Patel           30    75000
18                          24    58000
19     Isha Mehta           23    62000
20   Hemil Ghori            22    30000
21   Rahul Patel            22    35000
22     Nitin Shah           25    51000
23    Kajal Joshi           21      NaN
24       Om Patel          999  9999999
25      Tina Shah           19    27000
26   Vishal Mehta           33    88000
27     Maya Patel           26  invalid
28   Rakesh Kumar           28    72000
29     Nisha Shah           25    54000

In [37]:
df.head()
df.iloc[1:5, 2:5]

           age         city  gender
1          NaN        surat    male
2           21          NaN  Female
3  twenty-four    AHMEDABAD       M
4           23   ahmedabad        F

In [41]:
df.isnull()

       id   name    age   city  gender  salary  joining_date  department
0   False  False  False  False   False   False         False       False
1   False  False   True  False   False   False         False       False
2   False  False  False   True   False   False         False       False
3   False  False  False  False   False   False         False       False
4   False  False  False  False   False    True         False       False
5   False  False  False  False   False   False         False       False
6   False  False  False  False   False   False         False       False
7   False  False  False  False   False   False         False       False
8   False  False  False  False   False   False         False       False
9   False  False  False  False   False   False          True       False
10  False  False  False  False   False   False         False       False
11  False  False  False  False   False   False         False       False
12  False  False  False  False   False   False         False       False
13  False  False  False  False   False   False         False       False
14  False  False  False  False   False   False         False       False
15  False   True  False  False   False   False         False       False
16  False  False  False   True   False   False         False       False
17  False  False  False  False   False   False         False       False
18  False  False  False  False   False   False         False       False
19  False  False  False  False   False   False         False       False
20  False  False  False  False   False   False         False       False
21  False  False  False  False   False   False         False       False
22  False  False  False  False   False   False         False       False
23  False  False  False  False   False    True         False       False
24  False  False  False  False   False   False         False       False
25  False  False  False  False   False   False         False       False
26  False  False  False  False   False   False         False       False
27  False  False  False  False   False   False         False       False
28  False  False  False  False   False   False         False       False
29  False  False  False  False   False   False         False       False

In [42]:
df.isnull().sum()

id              0
name            1
age             1
city            2
gender          0
salary          2
joining_date    1
department      0
dtype: int64

In [43]:
df.isnull().mean() * 100

id              0.000000
name            3.333333
age             3.333333
city            6.666667
gender          0.000000
salary          6.666667
joining_date    3.333333
department      0.000000
dtype: float64

In [44]:
df[df.isna().any(axis=1)]

    id         name  age         city  gender  salary joining_date department
1    2  rahul patel  NaN        surat    male  35,000   15/02/2025       MERN
2    3   PRIYA SHAH   21          NaN  Female  ₹42000   2025/03/10      AI/ML
4    5   Neha Patel   23   ahmedabad        F     NaN   05-05-2025       data
9   10  Vivek Singh   26        Delhi    male   70000          NaN       MERN
15  16          NaN   27        Delhi    Male   65000   2025-11-20       Data
16  17  Anjali Shah   26          NaN  Female   52000   2025-12-01      AI/ML
23  24  Kajal Joshi   21         Pune  Female     NaN   2025-07-05      AI/ML

In [52]:
display(df.sample(5, random_state=42))

    id           name age       city  gender   salary joining_date department
27  28     Maya Patel  26      surat  Female  invalid   2025-07-25      AI/ML
15  16            NaN  27      Delhi    Male    65000   2025-11-20       Data
23  24    Kajal Joshi  21       Pune  Female      NaN   2025-07-05      AI/ML
17  18    Rohan Patel  30  Ahmedabad    Male    75000   2025-12-05       MERN
8    9    Sneha Desai  24      SURAT  Female            2025-08-01       Data

In [66]:
raw_df = df.copy()
clean_df = df.copy()

In [69]:
missing_markers = ["N/A", "NA", "NaN", "null", "NULL", "", " "]

clean_df = clean_df.replace(
    missing_markers,
    np.nan
)

clean_df.isna().sum()

id              0
name            1
age             1
city            2
gender          0
salary          3
joining_date    1
department      0
dtype: int64

In [71]:
df.isna().sum()

id              0
name            1
age             1
city            2
gender          0
salary          2
joining_date    1
department      0
dtype: int64

In [74]:
clean_df.columns = (
    clean_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

clean_df.columns

Index(['id', 'name', 'age', 'city', 'gender', 'salary', 'joining_date',
       'department'],
      dtype='str')

In [76]:
print("Duplicate rows before:", clean_df.duplicated().sum())

clean_df = clean_df.drop_duplicates().copy()

print("Duplicate rows after:", clean_df.duplicated().sum())

Duplicate rows before: 1
Duplicate rows after: 0

In [79]:
text_columns = clean_df.select_dtypes(include="object").columns
display(text_columns)
for col in text_columns:
    clean_df[col] = clean_df[col].str.strip()

clean_df[["name", "city", "gender", "department"]].head(10)

C:\Users\HEMIL\AppData\Local\Temp\ipykernel_28256\2846976107.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = clean_df.select_dtypes(include="object").columns

Index(['name', 'age', 'city', 'gender', 'salary', 'joining_date',
       'department'],
      dtype='str')

          name       city  gender department
0  Hemil Ghori      SURAT    Male      AI/ML
1  rahul patel      surat    male       MERN
2   PRIYA SHAH        NaN  Female      AI/ML
3   Amit Kumar  AHMEDABAD       M       Data
4   Neha Patel  ahmedabad       F       data
5    Raj Mehta     Mumbai    Male       MERN
6  Kiran Joshi       Pune  Female      AI/ML
7     Dev Shah     mumbai    Male      AI/ML
8  Sneha Desai      SURAT  Female       Data
9  Vivek Singh      Delhi    male       MERN

In [80]:
clean_df["city"] = clean_df["city"].str.lower().str.strip()

city_map = {
    "surat": "Surat",
    "ahmedabad": "Ahmedabad",
    "mumbai": "Mumbai",
    "bombay": "Mumbai",
    "pune": "Pune",
    "delhi": "Delhi"
}

clean_df["city"] = clean_df["city"].replace(city_map)

In [82]:
clean_df[[ "city" ]]

         city
0       Surat
1       Surat
2         NaN
3   Ahmedabad
4   Ahmedabad
5      Mumbai
6        Pune
7      Mumbai
8       Surat
9       Delhi
10      Surat
11     Mumbai
12  Ahmedabad
13       Pune
14      Surat
15      Delhi
16        NaN
17  Ahmedabad
18     Mumbai
19       Pune
21      Surat
22     Mumbai
23       Pune
24  Ahmedabad
25      Surat
26      Delhi
27      Surat
28  Ahmedabad
29       Pune

In [83]:
clean_df["gender"] = clean_df["gender"].str.lower().str.strip()

gender_map = {
    "m": "Male",
    "male": "Male",
    "f": "Female",
    "female": "Female"
}


clean_df["gender"] = clean_df["gender"].replace(gender_map)

In [84]:
clean_df[[ "gender" ]]

    gender
0     Male
1     Male
2   Female
3     Male
4   Female
5     Male
6   Female
7     Male
8   Female
9     Male
10  Female
11    Male
12    Male
13  Female
14    Male
15    Male
16  Female
17    Male
18  Female
19  Female
21    Male
22    Male
23  Female
24    Male
25  Female
26    Male
27  Female
28    Male
29  Female

In [85]:
clean_df["department"] = (
    clean_df["department"]
    .str.strip()
    .str.lower()
    .str.upper()
)

In [86]:
clean_df[[ "department" ]]

   department
0       AI/ML
1        MERN
2       AI/ML
3        DATA
4        DATA
5        MERN
6       AI/ML
7       AI/ML
8        DATA
9        MERN
10      AI/ML
11       MERN
12       DATA
13      AI/ML
14       MERN
15       DATA
16      AI/ML
17       MERN
18       DATA
19      AI/ML
21       MERN
22       DATA
23      AI/ML
24       MERN
25       DATA
26       MERN
27      AI/ML
28       DATA
29      AI/ML

In [87]:
display(clean_df[["city", "gender", "department"]].drop_duplicates().sort_values(
    ["city", "gender", "department"],
    na_position="last"
))

         city  gender department
4   Ahmedabad  Female       DATA
3   Ahmedabad    Male       DATA
17  Ahmedabad    Male       MERN
15      Delhi    Male       DATA
9       Delhi    Male       MERN
18     Mumbai  Female       DATA
7      Mumbai    Male      AI/ML
22     Mumbai    Male       DATA
5      Mumbai    Male       MERN
6        Pune  Female      AI/ML
10      Surat  Female      AI/ML
8       Surat  Female       DATA
0       Surat    Male      AI/ML
1       Surat    Male       MERN
2         NaN  Female      AI/ML

In [89]:
clean_df["name"] = clean_df["name"].replace(
    ["N/A", "NA", ""],
    np.nan
)

clean_df["name"] = clean_df["name"].str.strip().str.title()

clean_df["name"].head(10)

0    Hemil Ghori
1    Rahul Patel
2     Priya Shah
3     Amit Kumar
4     Neha Patel
5      Raj Mehta
6    Kiran Joshi
7       Dev Shah
8    Sneha Desai
9    Vivek Singh
Name: name, dtype: str

In [94]:
clean_df["age"] = pd.to_numeric(
    clean_df["age"],
    errors="coerce"
)

clean_df["age"].dtype

dtype('float64')

In [95]:
invalid_age = ~clean_df["age"].between(0, 100)

print("Invalid ages:")
display(clean_df.loc[invalid_age, ["id", "name", "age"]])

clean_df.loc[invalid_age, "age"] = np.nan

Invalid ages:

    id         name    age
1    2  Rahul Patel    NaN
3    4   Amit Kumar    NaN
6    7  Kiran Joshi  150.0
24  25     Om Patel  999.0

In [99]:
clean_df["salary"] = (
    clean_df["salary"]
    .astype("string")
    .str.strip()
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
)

clean_df["salary"] = pd.to_numeric(
    clean_df["salary"],
    errors="coerce"
)

clean_df["salary"].dtype

Int64Dtype()

In [103]:
invalid_salary = clean_df["salary"] < 0

print("Invalid salary records:")
display(clean_df.loc[invalid_salary, ["id", "name", "salary"]])

clean_df.loc[invalid_salary, "salary"] = np.nan

Invalid salary records:

Empty DataFrame
Columns: [id, name, salary]
Index: []

In [105]:
clean_df["joining_date"] = pd.to_datetime(
    clean_df["joining_date"],
    errors="coerce",
    dayfirst=True
)

clean_df["joining_date"].dtype

0    2025-01-15
1           NaT
2           NaT
3    2025-04-05
4           NaT
5    2025-06-12
6    2025-06-20
7           NaT
8    2025-08-01
9           NaT
10   2025-09-10
11   2025-10-11
12   2025-10-15
13   2025-11-01
14   2025-11-12
15   2025-11-20
16   2025-12-01
17   2025-12-05
18   2025-12-10
19   2025-12-15
21          NaT
22   2025-07-01
23   2025-07-05
24   2025-07-10
25   2025-07-15
26   2025-07-20
27   2025-07-25
28   2025-08-05
29   2025-08-10
Name: joining_date, dtype: datetime64[us]

In [106]:
clean_df["joining_year"] = clean_df["joining_date"].dt.year
clean_df["joining_month"] = clean_df["joining_date"].dt.month
clean_df["joining_day"] = clean_df["joining_date"].dt.day
clean_df["joining_day_name"] = clean_df["joining_date"].dt.day_name()

clean_df[[
    "joining_date",
    "joining_year",
    "joining_month",
    "joining_day",
    "joining_day_name"
]].head()

  joining_date  joining_year  joining_month  joining_day joining_day_name
0   2025-01-15        2025.0            1.0         15.0        Wednesday
1          NaT           NaN            NaN          NaN              NaN
2          NaT           NaN            NaN          NaN              NaN
3   2025-04-05        2025.0            4.0          5.0         Saturday
4          NaT           NaN            NaN          NaN              NaN

In [107]:
clean_df["age"] = clean_df["age"].fillna(clean_df["age"].median())
clean_df["salary"] = clean_df["salary"].fillna(clean_df["salary"].median())

for col in ["name", "city", "gender", "department"]:
    clean_df[col] = clean_df[col].fillna("Unknown")

print(clean_df.isna().sum())

id                  0
name                0
age                 0
city                0
gender              0
salary              0
joining_date        6
department          0
joining_year        6
joining_month       6
joining_day         6
joining_day_name    6
dtype: int64

In [108]:
for col in ["city", "gender", "department"]:
    print(f"\n{col}:")
    print(clean_df[col].value_counts(dropna=False))

city:
city
Surat        8
Ahmedabad    6
Mumbai       5
Pune         5
Delhi        3
Unknown      2
Name: count, dtype: int64

gender:
gender
Male      16
Female    13
Name: count, dtype: int64

department:
department
AI/ML    11
MERN      9
DATA      9
Name: count, dtype: int64

In [110]:
surat_records = clean_df[
    clean_df["city"] == "Surat"
]

high_salary = clean_df[
    clean_df["salary"] > 50000
]

ai_ml_adults = clean_df[
    (clean_df["department"] == "AI/ML") &
    (clean_df["age"] >= 18)
]

display(surat_records)
display(high_salary.head())
display(ai_ml_adults.head())

,id,name,age,city,gender,salary,joining_date,department,joining_year,joining_month,joining_day,joining_day_name
0,1,Hemil Ghori,22.0,Surat,Male,30000,2025-01-15,AI/ML,2025.0,1.0,15.0,Wednesday
1,2,Rahul Patel,25.0,Surat,Male,35000,NaT,MERN,NaN,NaN,NaN,NaN
8,9,Sneha Desai,24.0,Surat,Female,53000,2025-08-01,DATA,2025.0,8.0,1.0,Friday
10,11,Riya Shah,22.0,Surat,Female,48000,2025-09-10,AI/ML,2025.0,9.0,10.0,Wednesday
14,15,Jay Patel,28.0,Surat,Male,40000,2025-11-12,MERN,2025.0,11.0,12.0,Wednesday
21,2,Rahul Patel,22.0,Surat,Male,35000,NaT,MERN,NaN,NaN,NaN,NaN
25,26,Tina Shah,19.0,Surat,Female,27000,2025-07-15,DATA,2025.0,7.0,15.0,Tuesday
27,28,Maya Patel,26.0,Surat,Female,53000,2025-07-25,AI/ML,2025.0,7.0,25.0,Friday

,id,name,age,city,gender,salary,joining_date,department,joining_year,joining_month,joining_day,joining_day_name
4,5,Neha Patel,23.0,Ahmedabad,Female,53000,NaT,DATA,NaN,NaN,NaN,NaN
6,7,Kiran Joshi,25.0,Pune,Female,53000,2025-06-20,AI/ML,2025.0,6.0,20.0,Friday
7,8,Dev Shah,27.0,Mumbai,Male,60000,NaT,AI/ML,NaN,NaN,NaN,NaN
8,9,Sneha Desai,24.0,Surat,Female,53000,2025-08-01,DATA,2025.0,8.0,1.0,Friday
9,10,Vivek Singh,26.0,Delhi,Male,70000,NaT,MERN,NaN,NaN,NaN,NaN

,id,name,age,city,gender,salary,joining_date,department,joining_year,joining_month,joining_day,joining_day_name
0,1,Hemil Ghori,22.0,Surat,Male,30000,2025-01-15,AI/ML,2025.0,1.0,15.0,Wednesday
2,3,Priya Shah,21.0,Unknown,Female,42000,NaT,AI/ML,NaN,NaN,NaN,NaN
6,7,Kiran Joshi,25.0,Pune,Female,53000,2025-06-20,AI/ML,2025.0,6.0,20.0,Friday
7,8,Dev Shah,27.0,Mumbai,Male,60000,NaT,AI/ML,NaN,NaN,NaN,NaN
10,11,Riya Shah,22.0,Surat,Female,48000,2025-09-10,AI/ML,2025.0,9.0,10.0,Wednesday

In [111]:
clean_df["monthly_salary"] = clean_df["salary"] / 12

clean_df["age_group"] = np.where(
    clean_df["age"] >= 25,
    "25+",
    "Under 25"
)

clean_df[[
    "name",
    "age",
    "age_group",
    "salary",
    "monthly_salary"
]].head()

          name   age age_group  salary  monthly_salary
0  Hemil Ghori  22.0  Under 25   30000          2500.0
1  Rahul Patel  25.0       25+   35000     2916.666667
2   Priya Shah  21.0  Under 25   42000          3500.0
3   Amit Kumar  25.0       25+   45000          3750.0
4   Neha Patel  23.0  Under 25   53000     4416.666667

In [112]:
Q1 = clean_df["salary"].quantile(0.25)
Q3 = clean_df["salary"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

outliers = clean_df[
    (clean_df["salary"] < lower_bound) |
    (clean_df["salary"] > upper_bound)
]

display(outliers[["id", "name", "salary"]])

Q1: 45000.0
Q3: 65000.0
IQR: 20000.0
Lower bound: 15000.0
Upper bound: 95000.0

    id      name   salary
24  25  Om Patel  9999999

In [113]:
clean_df["salary"] = clean_df["salary"].clip(
    lower=lower_bound,
    upper=upper_bound
)

clean_df["salary"].describe()

count            29.0
mean     55655.172414
std        18270.3426
min           25000.0
25%           45000.0
50%           53000.0
75%           65000.0
max           95000.0
Name: salary, dtype: Float64

In [114]:
encoded_df = pd.get_dummies(
    clean_df,
    columns=["city", "gender", "department"],
    dtype=int
)

encoded_df.head()

,id,name,age,salary,joining_date,joining_year,joining_month,joining_day,joining_day_name,monthly_salary,...,city_Delhi,city_Mumbai,city_Pune,city_Surat,city_Unknown,gender_Female,gender_Male,department_AI/ML,department_DATA,department_MERN
0,1,Hemil Ghori,22.0,30000,2025-01-15,2025.0,1.0,15.0,Wednesday,2500.0,...,0,0,0,1,0,0,1,1,0,0
1,2,Rahul Patel,25.0,35000,NaT,NaN,NaN,NaN,NaN,2916.666667,...,0,0,0,1,0,0,1,0,0,1
2,3,Priya Shah,21.0,42000,NaT,NaN,NaN,NaN,NaN,3500.0,...,0,0,0,0,1,1,0,1,0,0
3,4,Amit Kumar,25.0,45000,2025-04-05,2025.0,4.0,5.0,Saturday,3750.0,...,0,0,0,0,0,0,1,0,1,0
4,5,Neha Patel,23.0,53000,NaT,NaN,NaN,NaN,NaN,4416.666667,...,0,0,0,0,0,1,0,0,1,0

In [115]:
salary_min = clean_df["salary"].min()
salary_max = clean_df["salary"].max()

if salary_max != salary_min:
    clean_df["salary_scaled"] = (
        (clean_df["salary"] - salary_min) /
        (salary_max - salary_min)
    )
else:
    clean_df["salary_scaled"] = 0

clean_df[["salary", "salary_scaled"]].head()

   salary  salary_scaled
0   30000       0.071429
1   35000       0.142857
2   42000       0.242857
3   45000       0.285714
4   53000            0.4

In [118]:
department_summary = clean_df.groupby("department"
    )["salary"].agg(
    ["count", "mean", "min", "max"]
)

department_summary

            count          mean    min    max
department
AI/ML          11  48363.636364  25000  62000
DATA            9  57111.111111  27000  90000
MERN            9  63111.111111  35000  95000

In [119]:
print("Final shape:", clean_df.shape)
print("\nDuplicate rows:", clean_df.duplicated().sum())

print("\nMissing values:")
print(clean_df.isna().sum())

print("\nData types:")
print(clean_df.dtypes)

print("\nFinal statistics:")
display(clean_df.describe(include="all"))

Final shape: (29, 15)

Duplicate rows: 0

Missing values:
id                  0
name                0
age                 0
city                0
gender              0
salary              0
joining_date        6
department          0
joining_year        6
joining_month       6
joining_day         6
joining_day_name    6
monthly_salary      0
age_group           0
salary_scaled       0
dtype: int64

Data types:
id                           int64
name                           str
age                        float64
city                           str
gender                         str
salary                       Int64
joining_date        datetime64[us]
department                     str
joining_year               float64
joining_month              float64
joining_day                float64
joining_day_name               str
monthly_salary             Float64
age_group                      str
salary_scaled              Float64
dtype: object

Final statistics:

,id,name,age,city,gender,salary,joining_date,department,joining_year,joining_month,joining_day,joining_day_name,monthly_salary,age_group,salary_scaled
count,29.000000,29,29.000000,29,29,29.0,23,29,23.0,23.000000,23.000000,23,29.0,29,29.0
unique,NaN,27,NaN,6,2,<NA>,NaN,3,NaN,NaN,NaN,7,<NA>,2,<NA>
top,NaN,Rahul Patel,NaN,Surat,Male,<NA>,NaN,AI/ML,NaN,NaN,NaN,Wednesday,<NA>,25+,<NA>
freq,NaN,2,NaN,8,16,<NA>,NaN,11,NaN,NaN,NaN,5,<NA>,18,<NA>
mean,14.620690,NaN,25.068966,NaN,NaN,55655.172414,2025-08-22 13:33:54.782608,NaN,2025.0,8.391304,10.608696,NaN,33100.571839,NaN,0.437931
min,1.000000,NaN,19.000000,NaN,NaN,25000.0,2025-01-15 00:00:00,NaN,2025.0,1.000000,1.000000,NaN,2083.333333,NaN,0.0
25%,7.000000,NaN,23.000000,NaN,NaN,45000.0,2025-07-07 12:00:00,NaN,2025.0,7.000000,5.000000,NaN,3750.0,NaN,0.285714
50%,14.000000,NaN,25.000000,NaN,NaN,53000.0,2025-08-05 00:00:00,NaN,2025.0,8.000000,10.000000,NaN,4416.666667,NaN,0.4
75%,23.000000,NaN,27.000000,NaN,NaN,65000.0,2025-11-06 12:00:00,NaN,2025.0,11.000000,15.000000,NaN,5416.666667,NaN,0.571429
max,30.000000,NaN,33.000000,NaN,NaN,95000.0,2025-12-15 00:00:00,NaN,2025.0,12.000000,25.000000,NaN,833333.25,NaN,1.0
std,9.131632,NaN,3.272516,NaN,NaN,18270.3426,NaN,NaN,0.0,2.824232,6.906776,NaN,153912.840879,NaN,0.261005

In [123]:
clean_df["joining_year"].dtype

dtype('float64')

In [125]:
clean_df.to_csv(
    "cleaned_data_solution.csv",
    index=False
)

print("Saved: cleaned_data_solution.csv")

Saved: cleaned_data_solution.csv